# Generated by Django 5.2 on 2025-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productrent_alter_order_payment_method_rentalorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flash_sale_images/')),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Enter percentage for percent discount, or fixed amount for fixed discount', max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
