# Generated by Django 4.2.21 on 2025-10-16 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_flashsaleorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flash_sale_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.flashsaleproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'flash_sale_product')},
            },
        ),
    ]
