# Generated by Django 4.2.21 on 2025-10-16 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_flashsalecartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='flash_sale_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flashsaleproduct'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preorder_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.preorderproduct'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(choices=[('regular', 'Regular Product'), ('preorder', 'Pre-order Product'), ('flash_sale', 'Flash Sale Product')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
