# Generated by Django 4.2.21 on 2025-10-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cartitem_flash_sale_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashSaleCartItem',
        ),
    ]
