# Generated by Django 4.2.21 on 2025-10-16 20:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_delete_flashsalecartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product_type', 'product', 'preorder_product', 'flash_sale_product')},
        ),
    ]
